networks:
  web:
    external: true
  backend:

services:
  rabbit:
    image: beevelop/rabbitmq-stomp
    networks:
    - web
    - backend
    env_file: ./config.env
    expose:
    - "15674"
    logging:
      driver: "local"
      options:
        max-size: "30m"
        max-file: "2"
    restart: unless-stopped

  server:
    build: ./src/codycolor-server
    networks:
    - backend
    env_file: ./config.env
    depends_on:
    - rabbit
    - database
    logging:
      driver: "local"
      options:
        max-size: "30m"
        max-file: "2"
    restart: unless-stopped

  database:
    image: mysql:5.7.44
    networks:
    - backend
    env_file: ./config.env
    logging:
      driver: "none"
    restart: unless-stopped

  database-client:
    build: ./src/database-client
    depends_on:
    - database
    networks:
    - backend
    env_file: ./config.env
    logging:
      driver: "none"

  database-manager:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
    - database
    networks:
    - web
    - backend
    env_file: ./config.env
    environment:
    - "PMA_HOST=database"
    - "UPLOAD_LIMIT=100M"
    expose:
    - "80"
    stdin_open: true
    tty: true
    logging:
      driver: "none"
