volumes:
  codycolor-data:
    external: true
  codycolor-database2:
    external: true

services:
  rabbit:
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=15674"
    - "traefik.frontend.entryPoints=https"
    - "traefik.frontend.rule=Host:codycolor.codemooc.net;PathPrefixStrip:/api"

  server:
    volumes:
    - codycolor-data:/data:rw

  database:
    volumes:
    - codycolor-database2:/var/lib/mysql:rw

  database-manager:
    environment:
    - "PMA_ABSOLUTE_URI=https://codycolor.codemooc.net/phpmyadmin/"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:codycolor.codemooc.net;PathPrefixStrip:/phpmyadmin/"
    - "traefik.frontend.entryPoints=https"
