/*
 * database.js: fornisce utilities per la connessione al db
 */
(function () {
    let mysql = require('mysql');
    let utils = require("./utils");

    const connection = mysql.createConnection({
        host: 'database',
        user: process.env.MYSQL_USER,
        password: process.env.MYSQL_PASSWORD,
        database: process.env.MYSQL_DATABASE,
        multipleStatements: true // possono essere effettuate query multiple.
    });
    connection.connect();


    module.exports.query = function(query, handleResults) {
        connection.query(query, (error, results) => {
            if (error) {
                utils.printLog("Error querying the DB. " + error.toString());
                utils.printLog("Error generated by the query " + query);
            } else
                utils.printLog("DB queried with success.");

            if (handleResults !== undefined)
                handleResults(results, error)
        });
    };


    module.exports.escape = function (value) {
        return connection.escape(value);
    }
}());