version: '3'

volumes:
  codycolor-data:
    external: true
  codycolor-database:
    external: true
  codycolor-influx:
    external: true

networks:
  web:
    external: true
  backend:

services:
  rabbit:
    image: beevelop/rabbitmq-stomp
    networks:
    - web
    - backend
    env_file: ../config.env
    expose:
    - "15674"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=15674"
    - "traefik.frontend.entryPoints=https"

  server:
    build: ../src/codycolor-server
    networks:
    - backend
    env_file: ../config.env
    depends_on:
    - rabbit
    - database
    - influx
    volumes:
    - codycolor-data:/data:rw

  database:
    image: mysql:5.7
    networks:
    - backend
    env_file: ../config.env
    volumes:
    - codycolor-database:/var/lib/mysql:rw

  database-client:
    build: ../src/database-client
    depends_on:
    - database
    networks:
    - backend
    env_file: ../config.env

  influx:
    image: influxdb:1.5.4-alpine
    env_file: ../config.env
    networks:
    - backend
    volumes:
    - codycolor-influx:/var/lib/influxdb:rw
    environment:
    - INFLUXDB_DB=codycolor

  grafana:
    image: grafana/grafana:6.2.1
    env_file: ../config.env
    networks:
    - web
    - backend
    expose:
    - "3000"
    environment:
    - GF_SERVER_ROOT_URL=https://codycolor-beta.codemooc.net/grafana
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=3000"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
